version: '3'

services:
  nginx:
    build: ./confs/nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '5000:5000'
      - '8082:8082'
    volumes:
      - ./confs/certbot/conf:/etc/letsencrypt
      - ./confs/certbot/www:/usr/share/nginx/html
    links:
      - nexus
    command: [ nginx, '-g', 'daemon off;' ]
  certbot:
    build: ./confs/certbot
    restart: unless-stopped
    volumes:
      - ./confs/certbot/conf:/etc/letsencrypt
      - ./confs/certbot/www:/var/www/certbot
  nexus:
    restart: always
    image: sonatype/nexus3
    volumes:
    - ./nexus-data:/nexus-data
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

